### ISSUE TITLE
soleng-presence-client repo missing

### ISSUE THREAD

**Issue by phpology** [fuze/soleng-ActionCommander#5]
Hi guys,

I know its been like 2 years since any updates to this repo but I was referred to this package as the best thing solution to the problem I was having in trying to 'get details of the incoming call'.

Altho there is a prebuilt .exe file available, I wanted to style up the ActionCommander windows so tried to install it locally via NPM. Got it running but none of my call presence status were working and looking at the console it was due to presence client missing.
The package.json references 2 paths which no longer exist, one of them being the soleng presence client. 
Any chance you can add this repo back in so that I can play please?

thanks, 
Raj from Your World Recruitment
D Wooldridge is our contact at Fuze.

**Comment by ifrias-fuze** [comment]
Hi @phpology, it should be available now.

**Comment by phpology** [comment]
Thanks @ifrias-fuze, will continue to play next week.
