### ISSUE TITLE
The release and source zips not related

### ISSUE THREAD

**Issue by phpology** [fuze/soleng-ActionCommander#6]
Hey guys,

How you doing?

Sorry to bother you, altho maybe me being slow today, but I think on this URL: 
https://github.com/fuze/soleng-ActionCommander/releases/tag/v0.0.2 - the source code is not related to the .msi file. 
When I open the package.json file it references 0.0.1 but the .msi is actually 0.0.2 and when I run the package locally, the settings button does not appear and the settings Call Event Triggers section is not visible.

Any chance you can upload the 0.0.2 source code please?

thanks

Raj

**Comment by soggypretzels** [comment]
Hello Raj,

Please try downloading the source code for the branch "general improvements" as this should be the latest version. If you have further questions or issues, please reach out to your contact at Fuze so we can look into the best way to provide assistance.
